name: ZgPHP Meetup
description: Druženja PHP developera iz Zagreba i okolice
url: http://www.zgphp.org

markdown: redcarpet
pygments: true
timezone: Europe/Zagreb
permalink: /:year/:month/:title

pagination: true
paginate: 20

# Custom configuration, not related to jekyll
custom:
    disqus:
        enabled: true
        shortname: zgphp
