name: ZgPHP Meetup
markdown: redcarpet
pygments: true
timezone: Europe/Zagreb
#paginate: 10
permalink: /:year/:month/:title

# Custom configuration, not related to jekyll
custom:
    disqus:
        enabled: true
        shortname: zgphptrial
